import 'core-js/features/array';
import 'core-js/features/object';
import 'core-js/features/map';
import 'core-js/features/weak-map';
import 'core-js/features/promise';
import 'core-js/features/number';
import 'core-js/features/string';
import 'core-js/features/regexp';
import 'core-js/features/reflect';
